### ISSUE TITLE
El Capitan

### ISSUE THREAD

**Issue by edwardpayton** [adamdehaven/outlook-2011-notification-center#1]
Hey, this wasn't working for me after updating to El Capitan. I was getting "command not found" errors.

After some investigating it turned out changing the path to terminal-notifier needs to be absolute fixed my problem.

Changed

```
do shell script "terminal-notifier -title '" & messageSender & "' -subtitle '" & messageSubject & "' -message '" & messageContent & "' -sound 'Ping' -execute 'open -b com.microsoft.Outlook' "
```

to

```
do shell script "/usr/local/bin/terminal-notifier -title '" & messageSender & "' -subtitle '" & messageSubject & "' -message '" & messageContent & "' -sound 'Ping' -execute 'open -b com.microsoft.Outlook' "
```

My fork with the change is here: https://github.com/edwardpayton/outlook-2011-notification-center

**Comment by adamdehaven** [comment]
@edwardpayton I'm not sure how I didn't catch this when I was running on my local machine. I have some alias commands and I'm betting I had one set up for terminal-notifier. I don't see a pull request from your fork, so I'll push a fix and you can just pull the upstream to your fork.
